### ISSUE TITLE
Simple Chatbot Install Fails

### ISSUE THREAD

**Issue by mynumu** [daily-co/dailyai-examples#10]
Hello - have popped this on your discord also

Trying to run the simple chatbot but not able to install dailyai at all. Tried via a manual pip install same issues

ERROR: Cannot install dailyai[daily,openai]==0.0.2, dailyai[daily,openai]==0.0.3, dailyai[daily,openai]==0.0.4, dailyai[daily,openai]==0.0.5, dailyai[daily,openai]==0.0.6, dailyai[daily,openai]==0.0.7 and dailyai[daily,openai]==0.0.8 because these package versions have conflicting dependencies.

Running windows 10 venv. Let me know if it will run on linux only and will try it over there thanks

[dailyissue.txt](https://github.com/daily-co/dailyai-examples/files/14971626/dailyissue.txt)

**Comment by aconchillo** [comment]
Hi @mynumu . Unfortunately, right now, the [daily] dependency requires Linux or macOS. I'll be closing this. Let us know if you run into any other issues.
